
services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpas
      MYSQL_DATABASE: website
      MYSQL_USER: "lori"
      MYSQL_PASSWORD: "!Spectre187"
    volumes:
      - website_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    container_name: spectre-api
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  website_db_data:
